// Generated by Selenium IDE
package org.example.Firefox;

import static org.example.Utils.fluentWait;
import static org.example.Utils.fluentWaitForClickable;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.example.config.ConfigReader;
import org.example.config.FirefoxConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;

public class GoogleloginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  private final String EMAIL = ConfigReader.getProperty("email");;
  private final String PASSWORD = ConfigReader.getProperty("password");;

  @BeforeEach
  public void setUp() {
    driver = FirefoxConfig.getFirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  private void fillGoogleLoginForm() {
    // try {
    // fluentWait(driver, By.xpath("//*[@id='identifierId']")).sendKeys(EMAIL);
    // fluentWaitForClickable(driver,
    // By.xpath("/html/body/div[1]/div[1]/div[2]/c-wiz/div/div[3]/div/div[1]/div/div/button/span"));
    // fluentWait(driver, By.xpath("//input[@type='password']")).sendKeys(PASSWORD);
    // fluentWaitForClickable(driver,
    // By.xpath("/html/body/div[1]/div[1]/div[2]/c-wiz/div/div[3]/div/div[1]/div/div/button/span"));
    // } catch (Exception e) {
    // System.out.println("Error during Google login: " + e.getMessage());
    // throw e;
    // }

    fluentWaitForClickable(driver, By.xpath("button[@id='primary-button-menu-trigger']/span/span"), 180, 15);
  }

  // @Test
  public void googlelogin() {
    driver.get("https://www.dropbox.com/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    fluentWaitForClickable(driver, By.xpath("//div/div/div[2]/a/div/span"));
    fluentWaitForClickable(driver, By.xpath("//div[2]/div/div/div/div/div/div[2]/div"));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[2]/div/div/div/div/div/div[2]/div")).click();
    vars.put("win971", waitForWindow(20000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win971").toString());
    fillGoogleLoginForm();

    // driver.findElement(By.xpath("//li/div/div/div/div[2]/div")).click();
    driver.switchTo().window(vars.get("root").toString());
    fluentWait(driver, By.xpath("//button[@id=\'primary-button-menu-trigger\']/span/span"));
  }
}
