services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "hibernatedb"
      POSTGRES_USER: "hibernateuser"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432" 

  minio:
    image: minio/minio:latest
    command: server --address localhost:9000 /data
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO Console port
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: secret_key
    volumes:
      - minio_data:/data  # Persistent storage

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgresql:
  minio-data:
