// Generated by Selenium IDE
package org.example.Chrome;

import static org.example.Utils.fluentWait;
import static org.example.Utils.fluentWaitForClickable;

import java.util.HashMap;
import java.util.Map;

import org.example.config.ConfigReader;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class RegisterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  private final String EMAIL = ConfigReader.getProperty("email.reg");
  private final String PASSWORD = ConfigReader.getProperty("password");
  private final String NAME = ConfigReader.getProperty("name");
  private final String SURNAME = ConfigReader.getProperty("surname");

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  // @Test
  public void registertest() {
    driver.get("https://www.dropbox.com/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    fluentWaitForClickable(driver, By.xpath("//div/div/div[2]/a/div/span"));
    fluentWait(driver, By.xpath(
        "//div[@id=\'login-or-register-page-content\']/div/div/div/div/div/div[2]/div/div[3]/form/div/div/input")
        )
        .sendKeys(EMAIL);
    fluentWaitForClickable(driver, By.cssSelector(".email-submit-button"));
    fluentWait(driver, By.xpath(
        "//div[@id=\'login-or-register-page-content\']/div/div/div/div/div/div[2]/div/div[4]/div/form/div/div/div[2]/div/div/div/input")
        )
        .sendKeys(NAME);
    fluentWait(driver, By.xpath(
        "//div[@id=\'login-or-register-page-content\']/div/div/div/div/div/div[2]/div/div[4]/div/form/div/div/div[2]/div[2]/div/div/input")
        )
        .sendKeys(SURNAME);
    fluentWait(driver, By.xpath(
        "//div[@id=\'login-or-register-page-content\']/div/div/div/div/div/div[2]/div/div[4]/div/form/div/div[2]/div/div/input")
        )
        .sendKeys(PASSWORD);

    fluentWaitForClickable(driver,
        By.xpath(
            "//div[@id='login-or-register-page-content']/div/div/div/div/div/div[2]/div/div[4]/div/form/button")
        );

    fluentWait(driver, By.xpath("//span/div/div/div/div/div/div/button/span/span"), 180, 15);
  }
}
